apiVersion: v1
kind: Service
metadata:
  name: provisioning-reference-api-service-dev-1
  labels:
    app: pra-dev-1
spec:
  type: LoadBalancer
  ports:
    - name: expose
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: ingest
      protocol: TCP
      port: 8889
      targetPort: 8889
  selector:
    app: pra-dev-1

